/*
 * Copyright (c) 2006-2021, RT-Thread Development Team
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Change Logs:
 * Date           Author       Notes
 * 2025-02-16     Cline        RT-Thread Nano configuration for GD32F303
 */

#ifndef RT_CONFIG_H__
#define RT_CONFIG_H__

/* Generated by Kconfiglib (https://github.com/ulfalizer/Kconfiglib) */

/* RT-Thread Kernel */

#define RT_NAME_MAX 8
#define RT_ALIGN_SIZE 4
#define RT_THREAD_PRIORITY_32
#define RT_THREAD_PRIORITY_MAX 32
#define RT_TICK_PER_SECOND 1000
#define RT_USING_OVERFLOW_CHECK
#define RT_USING_HOOK
#define RT_HOOK_USING_FUNC_PTR
#define RT_USING_IDLE_HOOK
#define RT_IDLE_HOOK_LIST_SIZE 4
#define IDLE_THREAD_STACK_SIZE 1024
#define RT_USING_TIMER_SOFT
#define RT_TIMER_THREAD_PRIO 4
#define RT_TIMER_THREAD_STACK_SIZE 1024

/* kservice optimization */

#define RT_KSERVICE_USING_STDLIB
#define RT_KSERVICE_USING_TINY_SIZE
/* end of kservice optimization */

/* Inter-Thread communication */

#define RT_USING_SEMAPHORE
#define RT_USING_MUTEX
#define RT_USING_EVENT
// #define RT_USING_MAILBOX
#define RT_USING_MESSAGEQUEUE
/* end of Inter-Thread communication */

/* Memory Management */

#define RT_USING_MEMPOOL
#define RT_USING_MEMHEAP
#define RT_MEMHEAP_FAST_MODE
#define RT_USING_MEMHEAP_AS_HEAP
#define RT_USING_HEAP
/* end of Memory Management */

#define RT_DEBUG
/* Kernel Device Object */

#define RT_USING_DEVICE
#define RT_USING_CONSOLE
#define RT_CONSOLEBUF_SIZE 256
#define RT_CONSOLE_DEVICE_NAME "uart0"
/* end of Kernel Device Object */

/* RT-Thread Components */

#define RT_USING_COMPONENTS_INIT
#define RT_USING_USER_MAIN
#define RT_MAIN_THREAD_STACK_SIZE 2048
#define RT_MAIN_THREAD_PRIORITY 10
/* end of RT-Thread Components */

/* C++ features */
/* end of C++ features */

/* Command shell */

#define RT_USING_FINSH
#define FINSH_THREAD_NAME "tshell"
#define FINSH_USING_HISTORY
#define FINSH_HISTORY_LINES 5
#define FINSH_USING_SYMTAB
#define FINSH_USING_DESCRIPTION
#define FINSH_THREAD_PRIORITY 20
#define FINSH_THREAD_STACK_SIZE 4096
#define FINSH_CMD_SIZE 80
#define FINSH_USING_MSH
#define FINSH_USING_MSH_DEFAULT
#define FINSH_USING_MSH_ONLY
#define FINSH_ARG_MAX 10
/* end of Command shell */

/* Device virtual file system */
/* end of Device virtual file system */

/* Device Drivers */

#define RT_USING_DEVICE_IPC
#define RT_USING_SERIAL
#define RT_USING_SERIAL_V1
#define RT_SERIAL_RB_BUFSZ 64
/* end of Device Drivers */

/* Using USB */
/* end of Using USB */

/* POSIX layer and C standard library */

#define RT_USING_LIBC
#define RT_LIBC_USING_TIME
#define RT_LIBC_DEFAULT_TIMEZONE 8
/* end of POSIX layer and C standard library */

/* Network */

/* Socket abstraction layer */
/* end of Socket abstraction layer */

/* Network interface device */
/* end of Network interface device */

/* light weight TCP/IP stack */
/* end of light weight TCP/IP stack */

/* AT commands */
/* end of AT commands */

/* VBUS(Virtual Software BUS) */
/* end of VBUS(Virtual Software BUS) */

/* Utilities */
/* end of Utilities */

/* RT-Thread Utestcases */
/* end of RT-Thread Utestcases */

/* RT-Thread online packages */

/* IoT - internet of things */
/* end of IoT - internet of things */

/* security packages */
/* end of security packages */

/* language packages */
/* end of language packages */

/* multimedia packages */
/* end of multimedia packages */

/* tools packages */
/* end of tools packages */

/* system packages */
/* end of system packages */

/* peripheral libraries and drivers */
/* end of peripheral libraries and drivers */

/* miscellaneous packages */
/* end of miscellaneous packages */

/* samples: kernel and components samples */
/* end of samples: kernel and components samples */

/* Hardware Drivers Config */

/* Onboard Peripheral Drivers */
/* end of Onboard Peripheral Drivers */

/* On-chip Peripheral Drivers */

#define BSP_USING_GPIO
#define BSP_USING_UART
#define BSP_USING_UART0
#define BSP_UART0_RX_USING_DMA
#define BSP_UART0_TX_USING_DMA
/* end of On-chip Peripheral Drivers */

/* Board extended module drivers */
/* end of Board extended module drivers */

/* GD32F303xC Configuration */

#define SOC_GD32F303xC
#define GD32F303xC
/* USE_STDPERIPH_DRIVER is defined in IAR project settings */
#define HXTAL_VALUE 8000000U
#define IRC8M_VALUE 8000000U
#define IRC48M_VALUE 48000000U
/* end of GD32F303xC Configuration */

#endif /* RT_CONFIG_H__ */