#ifndef _EVENT_H_
#define _EVENT_H_

enum SYSNC_EVENT
{
    SYNC_POWER_ON = 0,
    SYNC_SYSTEM_READY,
    SYNC_SYSTEM_SHUTDOWN,
    SYNC_SYSTEM_FAULT,
    SYNC_SYSTEM_RECOVER,
    SYNC_SYSTEM_KICKED,
    SYNC_ERROR_TRIGGERED,
    SYNC_ERROR_RELEASED,
    SYNC_OPERATE_DONE,
    SYNC_DLIB_PARA_CHANGED,
    SYNC_ERROR_TRIGGERED_LOG,
    SYNC_ERROR_RELEASED_LOG,
    SYNC_BATTERY_COTRL_MODE_CHANGED,
    SYNC_EVENT_MAX,
};

#endif
